apiVersion: v1
kind: Pod

metadata:
  name: pvc-test

spec:
  containers:
  - name: test-container
    image: nginx

    volumeMounts:
    - mountPath: /data
      name: test-storage

  volumes:
  - name: test-storage
    persistentVolumeClaim:
      claimName: mysql-pvc
